// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Eva_a4015406731486f4694c40c0ee0848a3Index = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Eva_a4015406731486f4694c40c0ee0848a3", 0 },

		};
	}
}
