// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_a4015406731486f4694c40c0ee0848a3_5a648de9_9fe3_4ac2_b739_4eeccc0ca181 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_a4015406731486f4694c40c0ee0848a3_4450f31f_52b7_4dda_a100_d6c1cd3a4dbe : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(coherenceSync.coherenceRotation);
			set => coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_a4015406731486f4694c40c0ee0848a3_e3251a5e_ac3c_466f_9079_50bb17feb9e9 : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Eva_UnityEngine__char_46_Animator_6841290336632632459";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent).Jump;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent;
			update.Jump = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Eva_UnityEngine__char_46_Animator_6841290336632632459();
		}
	}

	public class Binding_a4015406731486f4694c40c0ee0848a3_8babad3a_4967_42a1_9b76_d4fc9d87a71c : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Eva_UnityEngine__char_46_Animator_6841290336632632459";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent).Grounded;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent;
			update.Grounded = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Eva_UnityEngine__char_46_Animator_6841290336632632459();
		}
	}

	public class Binding_a4015406731486f4694c40c0ee0848a3_4fe2e979_113a_476f_ae35_14c2be362eaf : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Eva_UnityEngine__char_46_Animator_6841290336632632459";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent).FreeFall;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent;
			update.FreeFall = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Eva_UnityEngine__char_46_Animator_6841290336632632459();
		}
	}

	public class Binding_a4015406731486f4694c40c0ee0848a3_1bb6084c_8574_4054_8b35_35a616452050 : FloatAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Eva_UnityEngine__char_46_Animator_6841290336632632459";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override float Value
		{
			get => (float)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, (value));
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent).Speed;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent;
			update.Speed = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Eva_UnityEngine__char_46_Animator_6841290336632632459();
		}
	}

	public class Binding_a4015406731486f4694c40c0ee0848a3_09c95d48_5f1f_4395_ba08_e850cc5896a1 : FloatAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Eva_UnityEngine__char_46_Animator_6841290336632632459";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override float Value
		{
			get => (float)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, (value));
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent).MotionSpeed;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Eva_UnityEngine__char_46_Animator_6841290336632632459)coherenceComponent;
			update.MotionSpeed = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Eva_UnityEngine__char_46_Animator_6841290336632632459();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Eva' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncEva : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncEva>();
			if (coherenceSync.TryGetBindingByGuid("5a648de9-9fe3-4ac2-b739-4eeccc0ca181", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_a4015406731486f4694c40c0ee0848a3_5a648de9_9fe3_4ac2_b739_4eeccc0ca181();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("4450f31f-52b7-4dda-a100-d6c1cd3a4dbe", "rotation", out Binding InternalWorldOrientation_Rotation_value))
			{
				var clone = new Binding_a4015406731486f4694c40c0ee0848a3_4450f31f_52b7_4dda_a100_d6c1cd3a4dbe();
				InternalWorldOrientation_Rotation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldOrientation_Rotation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("e3251a5e-ac3c-466f-9079-50bb17feb9e9", "Jump", out Binding InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Jump))
			{
				var clone = new Binding_a4015406731486f4694c40c0ee0848a3_e3251a5e_ac3c_466f_9079_50bb17feb9e9();
				InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Jump.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Jump)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).Jump");
			}
			if (coherenceSync.TryGetBindingByGuid("8babad3a-4967-42a1-9b76-d4fc9d87a71c", "Grounded", out Binding InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Grounded))
			{
				var clone = new Binding_a4015406731486f4694c40c0ee0848a3_8babad3a_4967_42a1_9b76_d4fc9d87a71c();
				InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Grounded.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Grounded)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).Grounded");
			}
			if (coherenceSync.TryGetBindingByGuid("4fe2e979-113a-476f-ae35-14c2be362eaf", "FreeFall", out Binding InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_FreeFall))
			{
				var clone = new Binding_a4015406731486f4694c40c0ee0848a3_4fe2e979_113a_476f_ae35_14c2be362eaf();
				InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_FreeFall.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_FreeFall)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).FreeFall");
			}
			if (coherenceSync.TryGetBindingByGuid("1bb6084c-8574-4054-8b35-35a616452050", "Speed", out Binding InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Speed))
			{
				var clone = new Binding_a4015406731486f4694c40c0ee0848a3_1bb6084c_8574_4054_8b35_35a616452050();
				InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Speed.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_Speed)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).Speed");
			}
			if (coherenceSync.TryGetBindingByGuid("09c95d48-5f1f-4395-ba08-e850cc5896a1", "MotionSpeed", out Binding InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_MotionSpeed))
			{
				var clone = new Binding_a4015406731486f4694c40c0ee0848a3_09c95d48_5f1f_4395_ba08_e850cc5896a1();
				InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_MotionSpeed.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalEva_UnityEngine__char_46_Animator_6841290336632632459_Eva_UnityEngine__char_46_Animator_6841290336632632459_MotionSpeed)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).MotionSpeed");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncEva] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
